# Generated by Django 5.0.3 on 2024-04-03 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_complaint_remove_room_host_remove_room_participants_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='image_link',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='img',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
