# Generated by Django 5.0.3 on 2024-05-13 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_onlineclass'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onlineclass',
            old_name='phone_numbber',
            new_name='phone_number',
        ),
    ]
