# Generated by Django 5.0.3 on 2024-11-04 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_alter_onlineclass_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='body',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='categories',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='image_link',
            field=models.TextField(max_length=2000, null=True),
        ),
    ]
