# Generated by Django 5.0.3 on 2024-11-06 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_cbtquestion_course_department_keypoints_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='image',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='description',
        ),
    ]
