# Generated by Django 5.0.3 on 2024-11-06 20:20

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_remove_department_image_remove_topic_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='image',
        ),
        migrations.RemoveField(
            model_name='student',
            name='phone',
        ),
        migrations.AlterField(
            model_name='cbtquestion',
            name='question_text',
            field=ckeditor.fields.RichTextField(help_text='Question for the CBT'),
        ),
        migrations.AlterField(
            model_name='keypoints',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Key points or brief answers related to past questions'),
        ),
        migrations.AlterField(
            model_name='pastquestions',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='practiceexplanations',
            name='explanation',
            field=ckeditor.fields.RichTextField(help_text='Explanation for the correct answer in CBT'),
        ),
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRKKOdmJz8Z2pDtYgFgR2u9spABvNNPKYYtGw&s', max_length=5000, null=True, upload_to='uploaded_image'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
