# Generated by Django 5.0.3 on 2024-11-06 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_remove_course_image_remove_student_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cbtquestion',
            name='correct_option',
            field=models.SlugField(choices=[('A', 'Option A'), ('B', 'Option B'), ('C', 'Option C'), ('D', 'Option D')], max_length=1),
        ),
        migrations.AlterField(
            model_name='cbtquestion',
            name='option_a',
            field=models.SlugField(max_length=200),
        ),
        migrations.AlterField(
            model_name='cbtquestion',
            name='option_b',
            field=models.SlugField(max_length=200),
        ),
        migrations.AlterField(
            model_name='cbtquestion',
            name='option_c',
            field=models.SlugField(max_length=200),
        ),
        migrations.AlterField(
            model_name='cbtquestion',
            name='option_d',
            field=models.SlugField(max_length=200),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.SlugField(max_length=255),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.SlugField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pastquestions',
            name='year',
            field=models.SlugField(help_text='Year of the examination', max_length=4),
        ),
        migrations.AlterField(
            model_name='student',
            name='school',
            field=models.SlugField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.SlugField(max_length=255),
        ),
    ]
