# Generated by Django 5.0.3 on 2024-11-08 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_institutions_cbtquestion_percenntage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cbtquestion',
            name='percenntage',
            field=models.CharField(null=True),
        ),
    ]
