# Generated by Django 5.0.3 on 2024-11-08 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_alter_cbtquestion_percenntage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Institutions',
            new_name='Institution',
        ),
        migrations.RemoveField(
            model_name='cbtquestion',
            name='percenntage',
        ),
        migrations.AddField(
            model_name='cbtquestion',
            name='percentage',
            field=models.FloatField(blank=True, help_text='Score percentage for the question', null=True),
        ),
    ]
