# Generated by Django 5.0.3 on 2024-11-08 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0017_rename_institutions_institution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cbtquestion',
            name='percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
